[project]
name = "ollyoverend-dev"
version = "0.1.0"
description = "Olly Overend's personal website and blog"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs-material>=9.7.1",
]
